apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gym-dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: gym_order
  DATABASE_URL: postgresql://postgres:postgres@gym-order-postgres:15432/gym_order
